POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "Atomic Habits",
    "author" : "James Clear",
    "url" : "https://jamesclear.com/atomic-habits",
    "likes" : 89,
    "userId": "6201dac7b492540d5e03cdae"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
        "title": "React patterns",
        "author": "Michael Chan",
        "url": "https://reactpatterns.com/",
        "likes": 7,
        "userId":"6201dac7b492540d5e03cdae"
}


###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hellas",
    "name": "Arto Hellas",
    "password": "ah123123"
}


###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "ml123456"
}


###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "gigi",
    "name": "Grace C.",
    "password": "ml123456"
}



###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Grace",
    "password": "ml123456"
}



###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username" : "gigi",
    "password" : "ml123456"
}